# Copyright (C) 2015-2016 Skylable Ltd. <info-copyright@skylable.com>
# License: GPLv2 or later, see LICENSE for more details.

# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 11:14
from __future__ import unicode_literals

from django.db import migrations
import sxconsole.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20151122_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='level',
            field=sxconsole.utils.fields.ChoiceField(choices=[(b'1', 'Admin'), (b'2', 'Super Admin'), (b'3', 'Root Admin')], default=b'1', max_length=1, verbose_name='Level'),
        ),
    ]
