# Copyright (C) 2015-2016 Skylable Ltd. <info-copyright@skylable.com>
# License: GPLv2 or later, see LICENSE for more details.

# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 12:14
from __future__ import unicode_literals

from django.db import migrations
import sxconsole.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20160919_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='level',
            field=sxconsole.utils.fields.ChoiceField(choices=[(b'ADMIN', 'Admin'), (b'SUPER_ADMIN', 'Super Admin'), (b'ROOT_ADMIN', 'Root Admin')], default=b'ADMIN', max_length=11, verbose_name='Level'),
        ),
    ]
