# Copyright (C) 2015-2016 Skylable Ltd. <info-copyright@skylable.com>
# License: GPLv2 or later, see LICENSE for more details.

# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 11:14
from __future__ import unicode_literals

from django.db import migrations
import sxconsole.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0027_auto_20160510_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslogentrymodel',
            name='operation',
            field=sxconsole.utils.fields.ChoiceField(choices=[(b'1', 'List'), (b'2', 'Download'), (b'3', 'Upload'), (b'4', 'Delete')], max_length=1),
        ),
    ]
