# Copyright (C) 2015-2016 Skylable Ltd. <info-copyright@skylable.com>
# License: GPLv2 or later, see LICENSE for more details.

# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 12:22
from __future__ import unicode_literals

from django.db import migrations
import sxconsole.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0028_auto_20160919_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslogentrymodel',
            name='operation',
            field=sxconsole.utils.fields.ChoiceField(choices=[(b'LIST', 'List'), (b'DOWNLOAD', 'Download'), (b'UPLOAD', 'Upload'), (b'DELETE', 'Delete')], max_length=8),
        ),
    ]
