# Copyright (C) 2015-2016 Skylable Ltd. <info-copyright@skylable.com>
# License: GPLv2 or later, see LICENSE for more details.

# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 12:22
from __future__ import unicode_literals

from django.db import migrations


OPERATION_MAP = {
    '1': 'LIST',
    '2': 'DOWNLOAD',
    '3': 'UPLOAD',
    '4': 'DELETE',
}


def forwards(apps, schema_editor):
    AccessLogEntryModel = apps.get_model('clusters', 'AccessLogEntryModel')
    for old, new in OPERATION_MAP.items():
        AccessLogEntryModel.objects \
            .filter(operation=old) \
            .update(operation=new)


def backwards(apps, schema_editor):
    AccessLogEntryModel = apps.get_model('clusters', 'AccessLogEntryModel')
    for old, new in OPERATION_MAP.items():
        AccessLogEntryModel.objects \
            .filter(operation=new) \
            .update(operation=old)


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0029_auto_20160920_1222'),
    ]

    operations = [
        migrations.RunPython(
            forwards,
            backwards,
        ),
    ]
